// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBodiViwK-xZ4BWuEcCp91Gz_xjH19799M',
    appId: '1:1080548201876:web:c2fc06be8a8712e2142b81',
    messagingSenderId: '1080548201876',
    projectId: 'flutterproject-1aa37',
    authDomain: 'flutterproject-1aa37.firebaseapp.com',
    storageBucket: 'flutterproject-1aa37.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMfhKaCGCMZxpzVEfbPb6C2OUY0tU0nDU',
    appId: '1:1080548201876:android:3e9325432f29b02f142b81',
    messagingSenderId: '1080548201876',
    projectId: 'flutterproject-1aa37',
    storageBucket: 'flutterproject-1aa37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1jLXrMLQlt-fh_aQMsV33MCB5hjrgCho',
    appId: '1:1080548201876:ios:e51017fb15a65c0b142b81',
    messagingSenderId: '1080548201876',
    projectId: 'flutterproject-1aa37',
    storageBucket: 'flutterproject-1aa37.appspot.com',
    iosBundleId: 'com.example.objectdetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1jLXrMLQlt-fh_aQMsV33MCB5hjrgCho',
    appId: '1:1080548201876:ios:e51017fb15a65c0b142b81',
    messagingSenderId: '1080548201876',
    projectId: 'flutterproject-1aa37',
    storageBucket: 'flutterproject-1aa37.appspot.com',
    iosBundleId: 'com.example.objectdetection',
  );
}
